// vue/src/views/Tabs.vue
<template>
  <ion-page>
    <ion-tabs>
      <ion-tab-bar slot="bottom" v-if="shouldShowTabBar">
        <ion-tab-button tab="tab1" href="/tabs/tab1">
          <ion-icon :icon="triangle" />
          <ion-label>Tab 1</ion-label>
        </ion-tab-button>
          
        <ion-tab-button tab="tab2" href="/tabs/tab2">
          <ion-icon :icon="ellipse" />
          <ion-label>Tab 2</ion-label>
        </ion-tab-button>
        
        <ion-tab-button tab="tab3" href="/tabs/tab3">
          <ion-icon :icon="square" />
          <ion-label>Tab 3</ion-label>
        </ion-tab-button>
      </ion-tab-bar>
    </ion-tabs>
  </ion-page>
</template>

<script lang="ts">
import { IonTabBar, IonTabButton, IonTabs, IonLabel, IonIcon, IonPage } from '@ionic/vue';
import { ellipse, square, triangle } from 'ionicons/icons';
import { onMounted, onUnmounted, ref } from 'vue';

export default {
  name: 'Tabs',
  components: { IonLabel, IonTabs, IonTabBar, IonTabButton, IonIcon, IonPage },
  setup() {
    const shouldShowTabBar = ref(window.innerWidth < 992);
    const windowResized = () => shouldShowTabBar.value = window.innerWidth < 992;
    onMounted(() => window.addEventListener('resize', windowResized))
    onUnmounted(() => window.removeEventListener('resize', windowResized))
    return {
      ellipse,
      square,
      triangle,
      shouldShowTabBar,
      windowResized
    }
  }
}
</script>

// react/src/pages/Tabs.tsx
import { IonTabs, IonRouterOutlet, IonTabBar, IonTabButton, IonIcon, IonLabel } from '@ionic/react';
import { triangle, ellipse, square } from 'ionicons/icons';
import { Route, Redirect } from 'react-router';
import './Tabs.css';
import Tab2 from './Tab2';
import Tab3 from './Tab3';
import Tab1 from './Tab1';
import { useEffect, useState } from 'react';

const Tabs: React.FC = () => {
  const [width, setWidth] = useState(window.innerWidth);
  function widthChanged() {
    setWidth(window.innerWidth)
  }
  useEffect(() => {
    window.addEventListener('resize', widthChanged);
    return () => {
      window.removeEventListener('resize', widthChanged);
    }
  });

  return (
    <IonTabs>
      <IonRouterOutlet>
        <Route exact path="/tab1">
          <Tab1 />
        </Route>
        <Route exact path="/tab2">
          <Tab2 />
        </Route>
        <Route path="/tab3">
          <Tab3 />
        </Route>
        <Route exact path="/">
          <Redirect to="/tab1" />
        </Route>
      </IonRouterOutlet>
      <IonTabBar slot="bottom" style={{ display: width < 992 ? '' : 'none' }}>
        <IonTabButton tab="tab1" href="/tab1">
          <IonIcon icon={triangle} />
          <IonLabel>Tab 1</IonLabel>
        </IonTabButton>
        <IonTabButton tab="tab2" href="/tab2">
          <IonIcon icon={ellipse} />
          <IonLabel>Tab 2</IonLabel>
        </IonTabButton>
        <IonTabButton tab="tab3" href="/tab3">
          <IonIcon icon={square} />
          <IonLabel>Tab 3</IonLabel>
        </IonTabButton>
      </IonTabBar>
    </IonTabs>
  );
};

export default Tabs;
