// vue/src/views/SplitPane.vue
<template>
  <ion-split-pane contentId="menu-content">
    <ion-menu content-id="menu-content">
      <ion-header>
        <ion-toolbar>
          <ion-title>Pantry</ion-title>
        </ion-toolbar>
      </ion-header>
    </ion-menu>
    <ion-router-outlet id="menu-content" />
  </ion-split-pane>
</template>

<script lang="ts">
import {
  IonSplitPane,
  IonRouterOutlet,
  IonHeader,
  IonMenu,
  IonTitle,
  IonToolbar,
} from "@ionic/vue";

export default {
  name: "SplitPane",
  components: {
    IonSplitPane,
    IonRouterOutlet,
    IonHeader,
    IonMenu,
    IonTitle,
    IonToolbar,
  },
};
</script>

// react/src/components/SplitPane.tsx
import './SplitPane.css';
import { IonSplitPane, IonMenu, IonHeader, IonToolbar, IonTitle, IonRouterOutlet } from '@ionic/react';
import { Route } from 'react-router';
import { IonReactRouter } from '@ionic/react-router';
import Tabs from '../pages/Tabs';

const SplitPane: React.FC = () => {
  return (
    <IonReactRouter>
      <IonSplitPane contentId="menu-content">
        <IonMenu content-id="menu-content">
          <IonHeader>
            <IonToolbar>
              <IonTitle>Pantry</IonTitle>
            </IonToolbar>
          </IonHeader>
        </IonMenu>
        <IonRouterOutlet id="menu-content">
          <Route path="/">
            <Tabs></Tabs>
          </Route>
        </IonRouterOutlet>
      </IonSplitPane>
    </IonReactRouter>
  );
};

export default SplitPane;
