// angular/src/app/components/split-pane/split-pane.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-split-pane',
  templateUrl: './split-pane.component.html',
  styleUrls: ['./split-pane.component.scss'],
})
export class SplitPaneComponent implements OnInit {

  constructor() { }

  ngOnInit() {}

}

<ion-split-pane contentId="menu-content">
  <ion-menu content-id="menu-content">
    <ion-header>
      <ion-toolbar>
        <ion-title>Pantry</ion-title>
      </ion-toolbar>
    </ion-header>
  </ion-menu>
  <ion-router-outlet id="menu-content"></ion-router-outlet>
</ion-split-pane>

// vue/src/views/SplitPane.vue
<template>
  <ion-split-pane contentId="menu-content">
    <ion-menu content-id="menu-content">
      <ion-header>
        <ion-toolbar>
          <ion-title>Pantry</ion-title>
        </ion-toolbar>
      </ion-header>
    </ion-menu>
    <ion-router-outlet id="menu-content" />
  </ion-split-pane>
</template>

<script lang="ts">
import {
  IonSplitPane,
  IonRouterOutlet,
  IonHeader,
  IonMenu,
  IonTitle,
  IonToolbar,
} from "@ionic/vue";

export default {
  name: "SplitPane",
  components: {
    IonSplitPane,
    IonRouterOutlet,
    IonHeader,
    IonMenu,
    IonTitle,
    IonToolbar,
  },
};
</script>
